input.onButtonPressed(Button.A, function () {
    // Last Christmas (Simplified Full Version)
    // E5
    music.playTone(659, music.beat(BeatFraction.Quarter))
    // D5
    music.playTone(587, music.beat(BeatFraction.Quarter))
    // B4
    music.playTone(494, music.beat(BeatFraction.Half))
    // C5
    music.playTone(523, music.beat(BeatFraction.Quarter))
    // D5
    music.playTone(587, music.beat(BeatFraction.Quarter))
    // G4
    music.playTone(392, music.beat(BeatFraction.Half))
    // E5
    music.playTone(659, music.beat(BeatFraction.Quarter))
    // D5
    music.playTone(587, music.beat(BeatFraction.Quarter))
    // B4
    music.playTone(494, music.beat(BeatFraction.Half))
    // C5
    music.playTone(523, music.beat(BeatFraction.Quarter))
    // D5
    music.playTone(587, music.beat(BeatFraction.Quarter))
    // G4
    music.playTone(392, music.beat(BeatFraction.Half))
    // A4
    music.playTone(440, music.beat(BeatFraction.Quarter))
    // B4
    music.playTone(494, music.beat(BeatFraction.Quarter))
    // C5
    music.playTone(523, music.beat(BeatFraction.Half))
    // B4
    music.playTone(494, music.beat(BeatFraction.Quarter))
    // A4
    music.playTone(440, music.beat(BeatFraction.Quarter))
    // G4
    music.playTone(392, music.beat(BeatFraction.Half))
    // G4
    music.playTone(392, music.beat(BeatFraction.Quarter))
    // A4
    music.playTone(440, music.beat(BeatFraction.Quarter))
    // B4
    music.playTone(494, music.beat(BeatFraction.Half))
    // G4
    music.playTone(392, music.beat(BeatFraction.Quarter))
    // A4
    music.playTone(440, music.beat(BeatFraction.Quarter))
    // F#4
    music.playTone(370, music.beat(BeatFraction.Half))
})
input.onButtonPressed(Button.B, function () {
    // All I Want for Christmas Is You (Simplified Full Version)
    // E4
    music.playTone(330, music.beat(BeatFraction.Eighth))
    // E4
    music.playTone(330, music.beat(BeatFraction.Eighth))
    // E4
    music.playTone(330, music.beat(BeatFraction.Quarter))
    // E4
    music.playTone(330, music.beat(BeatFraction.Eighth))
    // E4
    music.playTone(330, music.beat(BeatFraction.Eighth))
    // E4
    music.playTone(330, music.beat(BeatFraction.Quarter))
    // E4
    music.playTone(330, music.beat(BeatFraction.Eighth))
    // G4
    music.playTone(392, music.beat(BeatFraction.Eighth))
    // C5
    music.playTone(523, music.beat(BeatFraction.Eighth))
    // B4
    music.playTone(494, music.beat(BeatFraction.Quarter))
    // A4
    music.playTone(440, music.beat(BeatFraction.Quarter))
    // E4
    music.playTone(330, music.beat(BeatFraction.Eighth))
    // E4
    music.playTone(330, music.beat(BeatFraction.Eighth))
    // E4
    music.playTone(330, music.beat(BeatFraction.Quarter))
    // E4
    music.playTone(330, music.beat(BeatFraction.Eighth))
    // E4
    music.playTone(330, music.beat(BeatFraction.Eighth))
    // E4
    music.playTone(330, music.beat(BeatFraction.Quarter))
    // E4
    music.playTone(330, music.beat(BeatFraction.Eighth))
    // G4
    music.playTone(392, music.beat(BeatFraction.Eighth))
    // C5
    music.playTone(523, music.beat(BeatFraction.Eighth))
    // B4
    music.playTone(494, music.beat(BeatFraction.Quarter))
    // A4
    music.playTone(440, music.beat(BeatFraction.Quarter))
    // G4
    music.playTone(392, music.beat(BeatFraction.Eighth))
    // F4
    music.playTone(349, music.beat(BeatFraction.Eighth))
    // E4
    music.playTone(330, music.beat(BeatFraction.Eighth))
    // D4
    music.playTone(294, music.beat(BeatFraction.Quarter))
    // G4
    music.playTone(392, music.beat(BeatFraction.Eighth))
    // G4
    music.playTone(392, music.beat(BeatFraction.Eighth))
    // G4
    music.playTone(392, music.beat(BeatFraction.Eighth))
    // G4
    music.playTone(392, music.beat(BeatFraction.Eighth))
    // G4
    music.playTone(392, music.beat(BeatFraction.Quarter))
})
